---
- hosts: pma
  vars_prompt:

    - name: rhel_user
      prompt: What is the subscription user?
      private: false

    - name: rhel_pass
      prompt: What is the subscription account password?
      private: true
  roles:
    - microshift
