---

- name: Register host with subscription manager
  community.general.redhat_subscription:
    state: present
    username: "{{ rhel_user }}"
    password: "{{ rhel_pass }}"
    auto_attach: true

- name: Enable MicroShift repos
  community.general.rhsm_repository:
    name: "rhocp-4.12-for-rhel-8-{{ uname }}-rpms"
      
      
