---

- name: Register host with subscription manager
  redhat_subscription:
    state: present
    username: "{{ rhel_user }}"
    password: "{{ rhel_pass }}"
    auto_attach: true

- name: Enable MicroShift repos
  rhsm_repository:
    name: 
      - "rhocp-4.12-for-rhel-8-{{ uname }}-rpms"
      - "fast-datapath-for-rhel-8-{{ uname }}-rpms"
      
- name: Install MicroShift with DNF
  ansible.builtin.dnf:
    name: microshift
    state: latest
    disable_gpg_check: true

- name: Copy Pull Secret
  copy:
    src: "{{ pull_secret_location }}"
    dest: /etc/crio/openshift-pull-secret
    owner: root
    group: root
    mode: '0600'

- name: Add firewall source
  ansible.posix.firewalld:
    zone: trusted
    source: 10.42.0.0/16
    permanent: true
    state: enabled

- name: Add firewall source 2
  ansible.posix.firewalld:
    zone: trusted
    source: 169.254.169.1
    permanent: true
    state: enabled

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Enable and start Microshift
  ansible.builtin.systemd:
    name: microshift
    state: started
    enabled: true

- name: Copy OC client
  copy:
    src: "{{ oc_client_location }}"
    dest: "/home/admin/{{oc_client}}"
    owner: admin
    group: admin
    mode: '0755'

- name: Install OC client
  ansible.builtin.dnf:
    name: "/home/admin/{{oc_client}}"
    state: present

- name: Make .kube dir
  ansible.builtin.file:
    path: /home/admin/.kube/
    state: directory
    mode: '0755'

- name: Copy kubeconfig file
  copy:
    src: "/var/lib/microshift/resources/kubeadmin/kubeconfig"
    dest: /home/admin/.kube/config
    owner: admin
    group: admin
    mode: '0700'

- name: Verify MicroShift is running
  ansible.builtin.shell:
    cmd: oc get all -A

